install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.55.4/hugo_0.58.2_Linux-64bit.deb
  - sudo dpkg -i hugo_0.58.2_Linux-64bit.deb
script:
  - hugodeploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      branch: master