install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.58.2/hugo_extended_0.58.2_Linux-64bit.deb
  - sudo apt-get update && sudo apt-get install npm
  - npm install postcss-cli
  - sudo dpkg -i hugo_extended_0.58.2_Linux-64bit.deb
script:
  - hugo

deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      branch: master
